const songs = [
  { title: "(Everything I Do) I Do It For You", artist: "Bryan Adams" },
  { title: "#41", artist: "Dave Matthews Band DMB" },
  { title: "1 2 3 4", artist: "Plain White T's" },
  { title: "100 Years", artist: "Five For Fighting" },
  { title: "1234", artist: "Feist" },
  { title: "1979", artist: "Smashing Pumpkins" },
  { title: "1985", artist: "Bowling For Soup" },
  { title: "3am", artist: "Matchbox Twenty" },
  { title: "6th Avenue Heartache", artist: "Wallflowers" },
  { title: "9 Crimes", artist: "Damien Rice" },
  { title: "A Hard Day's Night", artist: "Beatles" },
  { title: "A Lifetime", artist: "Better Than Ezra" },
  { title: "A Long December", artist: "Counting Crows" },
  { title: "A Simple Song 一手簡單的歌 Yi Shou Jian Dan De Ge", artist: "Leehom Wang 王力宏 Wang Lee Hom" },
  { title: "A Thousand Miles", artist: "Vanessa Carlton" },
  { title: "Absolutely (Story of a Girl)", artist: "Nine Days" },
  { title: "Accidentally In Love", artist: "Counting Crows" },
  { title: "Africa", artist: "Toto" },
  { title: "Against All Odds", artist: "Phil Collins" },
  { title: "Ain't No Mountain High Enough", artist: "Marvin Gaye & Tammi Terrell" },
  { title: "Ain't No Rest For The Wicked", artist: "Cage The Elephant" },
  { title: "Ain't No Sunshine", artist: "Bill Withers" },
  { title: "Alive", artist: "Pearl Jam" },
  { title: "All Along The Watchtower", artist: "Jimi Hendrix / Bob Dylan" },
  { title: "All For You", artist: "Sister Hazel" },
  { title: "All I Want", artist: "Kodaline" },
  { title: "All Of Me", artist: "John Legend" },
  { title: "All The Small Things", artist: "Blink 182" },
  { title: "All These Things That I've Done", artist: "Killers" },
  { title: "Amber", artist: "311" },
  { title: "American Girl", artist: "Tom Petty" },
  { title: "Angel", artist: "Sarah McLachlan" },
  { title: "Angel", artist: "Shaggy" },
  { title: "Anti-Hero", artist: "Taylor Swift" },
  { title: "Ants Marching", artist: "Dave Matthews Band DMB" },
  { title: "Apologize", artist: "One Republic" },
  { title: "As It Was", artist: "Harry Styles" },
  { title: "Atlantic City", artist: "Bruce Springsteen" },
  { title: "Baby One More Time", artist: "Britney Spears" },
  { title: "Baby Shark", artist: "Pinkfong" },
  { title: "Babylon", artist: "David Gray" },
  { title: "Back to the Past 回到過去 Hui Dao Guo Qu", artist: "Jay Chou 周杰倫 Zhou Jie Lun" },
  { title: "Bad Guy", artist: "Billie Eilish" },
  { title: "Bad Moon Rising", artist: "Creedence Clearwater Revival CCR" },
  { title: "Badfish", artist: "Sublime" },
  { title: "Bailamos", artist: "Enrique Iglesias" },
  { title: "Basketcase", artist: "Green Day" },
  { title: "Beautiful Day", artist: "U2" },
  { title: "Before You Go", artist: "Lewis Capaldi" },
  { title: "Best I Ever Had (Grey Sky Morning)", artist: "Vertical Horizon" },
  { title: "Better Man", artist: "Pearl Jam" },
  { title: "Better Together", artist: "Jack Johnson" },
  { title: "Big Yellow Taxi", artist: "Counting Crows / Joni Mitchell" },
  { title: "Billie Jean", artist: "Michael Jackson" },
  { title: "Bitter Sweet Symphony", artist: "The Verve" },
  { title: "Black Balloon", artist: "Goo Goo Dolls" },
  { title: "Black Humour 黑色幽默 Hei Se You Mo", artist: "Jay Chou 周杰倫 Zhou Jie Lun" },
  { title: "Blackbird", artist: "Beatles" },
  { title: "Blank Space", artist: "Taylor Swift" },
  { title: "Blinding Lights", artist: "The Weeknd" },
  { title: "Bloodbuzz Ohio", artist: "The National" },
  { title: "Blower's Daughter", artist: "Damien Rice" },
  { title: "Born In The USA", artist: "Bruce Springsteen" },
  { title: "Born To Run", artist: "Bruce Springsteen" },
  { title: "Boulevard of Broken Dreams", artist: "Green Day" },
  { title: "Boys Of Summer", artist: "Don Henley" },
  { title: "Breakdown", artist: "Tom Petty" },
  { title: "Breakeven", artist: "The Script" },
  { title: "Breakfast At Tiffany's", artist: "Deep Blue Something" },
  { title: "Bridge Over Troubled Water", artist: "Simon and Garfunkel" },
  { title: "Brown Eyed Girl", artist: "Van Morrison" },
  { title: "Budapest", artist: "George Ezra" },
  { title: "Bulletproof", artist: "La Roux" },
  { title: "Californication", artist: "Red Hot Chili Peppers RHCP" },
  { title: "Call Me Maybe", artist: "Carly Rae Jepsen" },
  { title: "Can't Help Falling In Love", artist: "Elvis Presley" },
  { title: "Can't Help Falling In Love With You 情非得已 Qing Fei De Yi", artist: "Harlem Yu 庾澄慶 Yu Chengqing" },
  { title: "Can't Stop", artist: "Red Hot Chili Peppers RHCP" },
  { title: "Cannonball", artist: "Damien Rice" },
  { title: "Castle On The Hill", artist: "Ed Sheeran" },
  { title: "Cath", artist: "Death Cab For Cutie" },
  { title: "Champagne Supernova", artist: "Oasis" },
  { title: "Chasing Cars", artist: "Snow Patrol" },
  { title: "Circles", artist: "Post Malone" },
  { title: "Clint Eastwood", artist: "Gorillaz" },
  { title: "Clocks", artist: "Coldplay" },
  { title: "Close To You 天天 Tian Tian", artist: "David Tao 陶喆 Tao Zhe" },
  { title: "Closer", artist: "Chainsmokers" },
  { title: "Closing Time", artist: "Semisonic" },
  { title: "Collide", artist: "Howie Day" },
  { title: "Come As You Are", artist: "Nirvana" },
  { title: "Come On Get Higher", artist: "Matt Nathanson" },
  { title: "Come To My Window", artist: "Melissa Etheridge" },
  { title: "Come Together", artist: "Beatles" },
  { title: "Complicated", artist: "Avril Lavigne" },
  { title: "Count On Me", artist: "Bruno Mars" },
  { title: "Counting Stars", artist: "One Republic" },
  { title: "Courage 勇氣 Yong Qi", artist: "Fish Leong 梁靜茹 Liang Jing Ru" },
  { title: "Crash Into Me", artist: "Dave Matthews Band DMB" },
  { title: "Crawling Back To You", artist: "Tom Petty" },
  { title: "Crazy", artist: "Aerosmith" },
  { title: "Crazy", artist: "Gnarls Barkley" },
  { title: "Crazy Little Thing Called Love", artist: "Queen" },
  { title: "Creep", artist: "Radiohead" },
  { title: "Crush", artist: "Dave Matthews Band DMB" },
  { title: "Dammit", artist: "Blink 182" },
  { title: "Dance Monkey", artist: "Tones and I" },
  { title: "Dancing In The Dark", artist: "Bruce Springsteen" },
  { title: "Dancing In The Moonlight", artist: "Toploader" },
  { title: "Dancing On My Own", artist: "Robyn / Calum Scott" },
  { title: "Dani California", artist: "Red Hot Chili Peppers RHCP" },
  { title: "Daughters", artist: "John Mayer" },
  { title: "Delicate", artist: "Damien Rice" },
  { title: "Demons", artist: "Imagine Dragons" },
  { title: "Desperado", artist: "Eagles" },
  { title: "Dirty Little Secret", artist: "All American Rejects" },
  { title: "Don't Let Me Down", artist: "Beatles" },
  { title: "Don't Look Back In Anger", artist: "Oasis" },
  { title: "Don't Panic", artist: "Coldplay" },
  { title: "Don't Start Now", artist: "Dua Lipa" },
  { title: "Don't Stop Believing", artist: "Journey" },
  { title: "Don't Worry Be Happy", artist: "Bobby McFerrin" },
  { title: "Don't You Forget About Me", artist: "Simple Minds" },
  { title: "Don't You Want Me", artist: "Human League" },
  { title: "Down Under", artist: "Men At Work" },
  { title: "Dreams", artist: "Cranberries" },
  { title: "Dreams", artist: "Fleetwood Mac" },
  { title: "Drift Away", artist: "Uncle Kracker / Dobie Gray" },
  { title: "Drive", artist: "Incubus" },
  { title: "Drive", artist: "The Cars" },
  { title: "Driver's License", artist: "Olivia Rodrigo" },
  { title: "Drops Of Jupiter", artist: "Train" },
  { title: "Easy", artist: "Commodores" },
  { title: "Edelweiss", artist: "Sound of Music Musical" },
  { title: "Edge of Seventeen", artist: "Fleetwood Mac / Stevie Nicks" },
  { title: "End Of The Road", artist: "Boyz II Men" },
  { title: "Escape (The Piña Colada Song)", artist: "Rupert Holmes" },
  { title: "Everlong", artist: "Foo Fighters" },
  { title: "Every Breath You Take", artist: "The Police" },
  { title: "Every Little Thing She Does Is Magic", artist: "The Police" },
  { title: "Everybody Wants To Rule The World", artist: "Tears For Fears" },
  { title: "Everything You Want", artist: "Vertical Horizon" },
  { title: "Everywhere", artist: "Michelle Branch" },
  { title: "Fade Into You", artist: "Mazzy Star" },
  { title: "Fairy Tale 童話 Tong Hua", artist: "Michael Wong 光良 Guang Liang" },
  { title: "Faith", artist: "George Michael" },
  { title: "Fake Plastic Trees", artist: "Radiohead" },
  { title: "Falling In Love At A Coffee Shop", artist: "Landon Pigg" },
  { title: "Falling Slowly", artist: "Glen Hansard and Marketa Irglova" },
  { title: "Fast Car", artist: "Tracy Chapman" },
  { title: "Father Of Mine", artist: "Everclear" },
  { title: "Fields of Gold", artist: "Sting" },
  { title: "Fireflies", artist: "Owl City" },
  { title: "Firework", artist: "Katy Perry" },
  { title: "Fix You", artist: "Coldplay" },
  { title: "Flagpole Sitta", artist: "Harvey Danger" },
  { title: "Follow Me", artist: "Uncle Kracker" },
  { title: "Follow You Down", artist: "Gin Blossoms" },
  { title: "For What It's Worth", artist: "Buffalo Springfield" },
  { title: "Forget You", artist: "Cee Lo Green" },
  { title: "Found Out About You", artist: "Gin Blossoms" },
  { title: "Free Falling", artist: "Tom Petty / John Mayer" },
  { title: "Friday I'm In Love", artist: "The Cure" },
  { title: "Funeral", artist: "Band of Horses" },
  { title: "Get Lucky", artist: "Daft Punk" },
  { title: "Give Me One Reason", artist: "Tracy Chapman" },
  { title: "Gives You Hell", artist: "All American Rejects" },
  { title: "Glycerine", artist: "Bush" },
  { title: "Good", artist: "Better Than Ezra" },
  { title: "Good 4 U", artist: "Olivia Rodrigo" },
  { title: "Good Life", artist: "One Republic" },
  { title: "Good Riddance (Time Of Your Life)", artist: "Green Day" },
  { title: "Good To Be Alone", artist: "Theo Katzman" },
  { title: "Goodbye To You", artist: "Michelle Branch" },
  { title: "Gravity", artist: "John Mayer" },
  { title: "Grenade", artist: "Bruno Mars" },
  { title: "Grey Street", artist: "Dave Matthews Band DMB" },
  { title: "Grow Old With You", artist: "Adam Sandler" },
  { title: "Hallelujah", artist: "Leonard Cohen / Jeff Buckley" },
  { title: "Hands Down", artist: "Dashboard Confessional" },
  { title: "Hanginaround", artist: "Counting Crows" },
  { title: "Hanging By A Moment", artist: "Lifehouse" },
  { title: "Happy Breakup 分手快樂 Fen Shou Kuai Le", artist: "Fish Leong 梁靜茹 Liang Jing Ru" },
  { title: "Harvest Moon", artist: "Neil Young" },
  { title: "Have You Ever Seen The Rain", artist: "Creedence Clearwater Revival CCR" },
  { title: "Heaven", artist: "Bryan Adams" },
  { title: "Helena", artist: "My Chemical Romance MCR" },
  { title: "Hemorrhage (In My Hands)", artist: "Fuel" },
  { title: "Here With Me", artist: "Dido" },
  { title: "Here Without You", artist: "3 Doors Down" },
  { title: "Here's To The Night", artist: "Eve 6" },
  { title: "Hero", artist: "Enrique Iglesias" },
  { title: "Hey Jealousy", artist: "Gin Blossoms" },
  { title: "Hey Jude", artist: "Beatles" },
  { title: "Hey Leonardo (She Likes Me for Me)", artist: "Blessid Union of Souls" },
  { title: "Hey Soul Sister", artist: "Train" },
  { title: "Hey There Delilah", artist: "Plain White T's" },
  { title: "Hey Ya", artist: "OutKast" },
  { title: "High And Dry", artist: "Radiohead" },
  { title: "Hit Me With Your Best Shot", artist: "Pat Benetar" },
  { title: "Ho Hey", artist: "Lumineers" },
  { title: "Hold On, We're Going Home", artist: "Drake" },
  { title: "Hold You In My Arms", artist: "Ray LaMontagne" },
  { title: "Holocene", artist: "Bon Iver" },
  { title: "Holy", artist: "Justin Bieber" },
  { title: "Home", artist: "Michael Buble" },
  { title: "Hook", artist: "Blues Traveler" },
  { title: "Horse With No Name", artist: "America" },
  { title: "Hotel California", artist: "Eagles" },
  { title: "House Of The Rising Sun", artist: "Animals" },
  { title: "How Am I Supposed To Live Without You", artist: "Michael Bolton" },
  { title: "How Sweet It Is", artist: "James Taylor" },
  { title: "How To Save A Life", artist: "The Fray" },
  { title: "How's It Gonna Be", artist: "Third Eye Blind" },
  { title: "Hungry Heart", artist: "Bruce Springsteen" },
  { title: "Hungry Like The Wolf", artist: "Duran Duran" },
  { title: "I Can't Make You Love Me", artist: "Bonnie Raitt" },
  { title: "I Don't Want To Miss A Thing", artist: "Aerosmith" },
  { title: "I Melt With You", artist: "Modern English" },
  { title: "I Miss You", artist: "Blink 182" },
  { title: "I Still Haven't Found What I'm Looking For", artist: "U2" },
  { title: "I Wanna Dance With Somebody", artist: "Whitney Houston" },
  { title: "I Want It That Way", artist: "Backstreet Boys" },
  { title: "I Will Buy You A New Life", artist: "Everclear" },
  { title: "I Will Follow You Into The Dark", artist: "Death Cab For Cutie" },
  { title: "I Will Survive", artist: "Gloria Gaynor / Cake" },
  { title: "I Will Wait", artist: "Mumford and Sons" },
  { title: "I Won't Back Down", artist: "Tom Petty" },
  { title: "I Won't Give Up", artist: "Jason Mraz" },
  { title: "I'll Be", artist: "Edwin McCain" },
  { title: "I'm Gonna Be (500 Miles)", artist: "Proclaimers" },
  { title: "I'm Not The Only One", artist: "Sam Smith" },
  { title: "I'm On Fire", artist: "Bruce Springsteen" },
  { title: "I'm Yours", artist: "Jason Mraz" },
  { title: "If I Ain't Got You", artist: "Alicia Keys" },
  { title: "If It Makes You Happy", artist: "Sheryl Crow" },
  { title: "If You Could Only See", artist: "Tonic" },
  { title: "If You're Gone", artist: "Matchbox Twenty" },
  { title: "Imagine", artist: "John Lennon" },
  { title: "In My Life", artist: "Beatles" },
  { title: "In The Air Tonight", artist: "Phil Collins" },
  { title: "In The End", artist: "Linkin Park" },
  { title: "Inside Out", artist: "Eve 6" },
  { title: "Interstate Love Song", artist: "Stone Temple Pilots STP" },
  { title: "Into The Mystic", artist: "Van Morrison" },
  { title: "Iris", artist: "Goo Goo Dolls" },
  { title: "Ironic", artist: "Alanis Morissette" },
  { title: "Is This Love", artist: "Bob Marley" },
  { title: "Island In The Sun", artist: "Weezer" },
  { title: "Islands In the Stream", artist: "Dolly Parton, Kenny Rogers" },
  { title: "It Ends Tonight", artist: "All American Rejects" },
  { title: "It Wasn't Me", artist: "Shaggy" },
  { title: "It Will Rain", artist: "Bruno Mars" },
  { title: "It's Been Awhile", artist: "Staind" },
  { title: "Jenny 867-5309", artist: "Tommy Tutone" },
  { title: "Jolene", artist: "Dolly Parton" },
  { title: "Jolene", artist: "Ray LaMontagne" },
  { title: "Jumper", artist: "Third Eye Blind" },
  { title: "Just The Two Of Us", artist: "Grover Washington Jr. & Bill Withers" },
  { title: "Just The Way You Are", artist: "Billy Joel" },
  { title: "Just The Way You Are", artist: "Bruno Mars" },
  { title: "Karma Chameleon", artist: "Culture Club" },
  { title: "Karma Police", artist: "Radiohead" },
  { title: "Kids", artist: "MGMT" },
  { title: "Killing Me Softly", artist: "Fugees" },
  { title: "King Of Wishful Thinking", artist: "Go West" },
  { title: "Kiss Goodbye", artist: "Leehom Wang 王力宏 Wang Lee Hom" },
  { title: "Kiss Me", artist: "Sixpence None The Richer" },
  { title: "Knockin' On Heaven's Door", artist: "Guns N Roses / Bob Dylan" },
  { title: "Kryptonite", artist: "3 Doors Down" },
  { title: "Landslide", artist: "Fleetwood Mac" },
  { title: "Last Christmas", artist: "Wham" },
  { title: "Last Friday Night TGIF", artist: "Katy Perry" },
  { title: "Last Kiss", artist: "Pearl Jam" },
  { title: "Last Nite", artist: "Strokes" },
  { title: "Layla", artist: "Eric Clapton" },
  { title: "Lazy Song", artist: "Bruno Mars" },
  { title: "Lean On Me", artist: "Bill Withers" },
  { title: "Learn To Fly", artist: "Foo Fighters" },
  { title: "Learning To Fly", artist: "Tom Petty" },
  { title: "Leaving On A Jet Plane", artist: "John Denver" },
  { title: "Lego House", artist: "Ed Sheeran" },
  { title: "Let Her Cry", artist: "Hootie & the Blowfish" },
  { title: "Let It Be", artist: "Beatles" },
  { title: "Let It Be Me", artist: "Ray LaMontagne" },
  { title: "Let It Go", artist: "James Bay" },
  { title: "Levitating", artist: "Dua Lipa" },
  { title: "Lightning Crashes", artist: "LIVE" },
  { title: "Linger", artist: "Cranberries" },
  { title: "Little Lion Man", artist: "Mumford and Sons" },
  { title: "Little Talks", artist: "Of Monsters And Men" },
  { title: "Living In Lightning", artist: "City And Colour" },
  { title: "Look What You've Done", artist: "Jet" },
  { title: "Losing My Religion", artist: "REM" },
  { title: "Lost Stars", artist: "Keira Knightley" },
  { title: "Love Confession Balloon 告白氣球 Gao Bai Qi Qiu", artist: "Jay Chou 周杰倫 Zhou Jie Lun" },
  { title: "Love Is Simple 愛很簡單 Ai Hen Jian Dan", artist: "David Tao 陶喆 Tao Zhe" },
  { title: "Love Me Don't Go 愛我別走 Ai Wo Bie Zou", artist: "A-Yue 張震嶽 Zhang Zhen Yue" },
  { title: "Love Song", artist: "311 / The Cure" },
  { title: "Love Story", artist: "Taylor Swift" },
  { title: "Love Yourself", artist: "Justin Bieber" },
  { title: "Low", artist: "Cracker" },
  { title: "Lucy In The Sky With Diamonds", artist: "Beatles" },
  { title: "Madness", artist: "Muse" },
  { title: "Make You Feel My Love", artist: "Adele / Bob Dylan" },
  { title: "Margaritaville", artist: "Jimmy Buffett" },
  { title: "Marry Me", artist: "Train" },
  { title: "Mary Jane's Last Dance", artist: "Tom Petty" },
  { title: "Meet Virginia", artist: "Train" },
  { title: "Message In A Bottle", artist: "The Police" },
  { title: "MMMBop", artist: "Hanson" },
  { title: "More Than Words", artist: "Extreme" },
  { title: "Move Along", artist: "All American Rejects" },
  { title: "Movin' Out (Anthony's Song)", artist: "Billy Joel" },
  { title: "Mr Jones", artist: "Counting Crows" },
  { title: "Mr. Brightside", artist: "Killers" },
  { title: "Mrs. Robinson", artist: "Simon and Garfunkel" },
  { title: "My Hero", artist: "Foo Fighters" },
  { title: "My Own Worst Enemy", artist: "Lit" },
  { title: "Need You Now", artist: "Lady A" },
  { title: "New Soul", artist: "Yael Naim" },
  { title: "No Woman No Cry", artist: "Bob Marley" },
  { title: "Numb", artist: "Linkin Park" },
  { title: "Octopus's Garden", artist: "Beatles" },
  { title: "One", artist: "U2" },
  { title: "One Call Away", artist: "Charlie Puth" },
  { title: "One Headlight", artist: "Wallflowers" },
  { title: "Only One 唯一 Wei Yi", artist: "Leehom Wang 王力宏 Wang Lee Hom" },
  { title: "Only Wanna Be With You", artist: "Hootie & the Blowfish" },
  { title: "Ophelia", artist: "Lumineers" },
  { title: "Otherside", artist: "Red Hot Chili Peppers RHCP" },
  { title: "Over My Head (Cable Car)", artist: "The Fray" },
  { title: "Over The Rainbow & What A Wonderful World", artist: "Israel Kamakawiwo'ole" },
  { title: "Paint It Black", artist: "Rolling Stones" },
  { title: "Peninsula Ironbox 半島鐵盒 Ban Dao Tie He", artist: "Jay Chou 周杰倫 Zhou Jie Lun" },
  { title: "Perfect", artist: "Ed Sheeran" },
  { title: "Perfect", artist: "Simple Plan" },
  { title: "Photograph", artist: "Ed Sheeran" },
  { title: "Piano Man", artist: "Billy Joel" },
  { title: "Picture", artist: "Kid Rock & Sheryl Crow" },
  { title: "Pink Pony Club", artist: "Chappell Roan" },
  { title: "Please Forgive Me", artist: "Bryan Adams" },
  { title: "Plush", artist: "Stone Temple Pilots STP" },
  { title: "Pompeii", artist: "Bastille" },
  { title: "Proud Mary", artist: "Creedence Clearwater Revival CCR / Tina Turner" },
  { title: "Psycho Killer", artist: "Talking Heads" },
  { title: "Pumped Up Kicks", artist: "Foster The People" },
  { title: "Push", artist: "Matchbox Twenty" },
  { title: "Put Your Records On", artist: "Corinne Bailey Rae" },
  { title: "Real World", artist: "Matchbox Twenty" },
  { title: "Red Red Wine", artist: "Neil Diamond / UB40" },
  { title: "Red Wine Supernova", artist: "Chappell Roan" },
  { title: "Redemption Song", artist: "Bob Marley" },
  { title: "Refugee", artist: "Tom Petty" },
  { title: "Renegades", artist: "X Ambassadors" },
  { title: "Rhiannon", artist: "Fleetwood Mac" },
  { title: "Riptide", artist: "Vance Joy" },
  { title: "Rocket Man", artist: "Elton John" },
  { title: "Rockin' In The Free World", artist: "Neil Young" },
  { title: "Rolling In The Deep", artist: "Adele" },
  { title: "Round Here", artist: "Counting Crows" },
  { title: "Royals", artist: "Lorde" },
  { title: "Rude", artist: "Magic!" },
  { title: "Run-Around", artist: "Blues Traveler" },
  { title: "Sail Away", artist: "David Gray" },
  { title: "Santa Monica", artist: "Everclear" },
  { title: "Santeria", artist: "Sublime" },
  { title: "Satellite", artist: "Dave Matthews Band DMB" },
  { title: "Save Tonight", artist: "Eagle Eye Cherry" },
  { title: "Save Your Tears", artist: "The Weeknd" },
  { title: "Say Hello Wave Goodbye", artist: "David Gray / Soft Cell" },
  { title: "Say It Ain't So", artist: "Weezer" },
  { title: "Say Something", artist: "A Great Big World" },
  { title: "Say You Won't Let Go", artist: "James Arthur" },
  { title: "Scar Tissue", artist: "Red Hot Chili Peppers RHCP" },
  { title: "Secret Garden", artist: "Bruce Springsteen" },
  { title: "Secrets", artist: "One Republic" },
  { title: "Semi Charmed Life", artist: "Third Eye Blind" },
  { title: "Seven Nation Army", artist: "White Stripes" },
  { title: "Sex and Candy", artist: "Marcy Playground" },
  { title: "Sex On Fire", artist: "Kings of Leon" },
  { title: "Shadow Of The Day", artist: "Linkin Park" },
  { title: "Shallow", artist: "Lady Gaga & Bradley Cooper" },
  { title: "Shape Of You", artist: "Ed Sheeran" },
  { title: "She Is Love", artist: "Parachute" },
  { title: "She Will Be Loved", artist: "Maroon 5" },
  { title: "Shotgun", artist: "George Ezra" },
  { title: "Shut Up And Dance", artist: "Walk The Moon" },
  { title: "Sideways", artist: "Citizen Cope" },
  { title: "Silence 安靜 An Jing", artist: "Jay Chou 周杰倫 Zhou Jie Lun" },
  { title: "Silver and Gold", artist: "City And Colour" },
  { title: "Simple Love 簡單愛 Jian Dan Ai", artist: "Jay Chou 周杰倫 Zhou Jie Lun" },
  { title: "Simple Man", artist: "Lynyrd Skynyrd" },
  { title: "Sitting On The Dock Of The Bay", artist: "Otis Redding" },
  { title: "Sitting Waiting Wishing", artist: "Jack Johnson" },
  { title: "Skinny Love", artist: "Bon Iver / Birdy" },
  { title: "Sleeping Sickness", artist: "City And Colour" },
  { title: "Slide", artist: "Goo Goo Dolls" },
  { title: "Slow Dancing In A Burning Room", artist: "John Mayer" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana" },
  { title: "Smile Like You Mean It", artist: "Killers" },
  { title: "Smooth", artist: "Santana ft. Rob Thomas" },
  { title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers RHCP" },
  { title: "Someone Like You", artist: "Adele" },
  { title: "Someone You Loved", artist: "Lewis Capaldi" },
  { title: "Something", artist: "Beatles" },
  { title: "Something", artist: "Julien Baker" },
  { title: "Somewhere Only We Know", artist: "Keane" },
  { title: "Sound Of Silence", artist: "Simon and Garfunkel" },
  { title: "Spanish Pipedream", artist: "John Prine" },
  { title: "Sparks", artist: "Coldplay" },
  { title: "Stable Song", artist: "Gregory Alan Isakov" },
  { title: "Stacy's Mom", artist: "Fountains of Wayne" },
  { title: "Stand By Me", artist: "Ben E. King" },
  { title: "Starlight", artist: "Muse" },
  { title: "Starry Mood 星晴 Xing Qing", artist: "Jay Chou 周杰倫 Zhou Jie Lun" },
  { title: "Stay With Me", artist: "Sam Smith" },
  { title: "Steal My Kisses", artist: "Ben Harper" },
  { title: "Still in Love With You 依然愛你 Yi Ran Ai Ni", artist: "Leehom Wang 王力宏 Wang Lee Hom" },
  { title: "Stuck In A Moment You Can't Get Out Of", artist: "U2" },
  { title: "Stuck In The Middle With You", artist: "Stealers Wheel" },
  { title: "Suddenly I See", artist: "KT Tunstall" },
  { title: "Sugar We're Going Down", artist: "Fall Out Boy" },
  { title: "Summer of 69", artist: "Bryan Adams" },
  { title: "Summertime Sadness", artist: "Lana Del Rey" },
  { title: "Sunday Morning", artist: "Maroon 5" },
  { title: "Sunny Came Home", artist: "Shawn Colvin" },
  { title: "Sunny Day 晴天 Qing Tian", artist: "Jay Chou 周杰倫 Zhou Jie Lun" },
  { title: "Superman (It’s Not Easy)", artist: "Five For Fighting" },
  { title: "Suspicious Minds", artist: "Elvis Presley" },
  { title: "Sweet Caroline", artist: "Neil Diamond" },
  { title: "Sweet Child O' Mine", artist: "Guns N Roses" },
  { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd" },
  { title: "Tainted Love", artist: "Soft Cell" },
  { title: "Take It Easy", artist: "Eagles" },
  { title: "Take Me Home Country Roads", artist: "John Denver" },
  { title: "Take Me Home Tonight", artist: "Eddie Money" },
  { title: "Take Me Out", artist: "Franz Ferdinand" },
  { title: "Take On Me", artist: "A-Ha" },
  { title: "Tears In Heaven", artist: "Eric Clapton" },
  { title: "Teenage Dirtbag", artist: "Wheatus" },
  { title: "Teenage Dream", artist: "Katy Perry" },
  { title: "Tennessee Whiskey", artist: "Chris Stapleton" },
  { title: "Thank U", artist: "Alanis Morissette" },
  { title: "Thank You", artist: "Dido" },
  { title: "The A Team", artist: "Ed Sheeran" },
  { title: "The Freshmen", artist: "Verve Pipe" },
  { title: "The Girl", artist: "City And Colour" },
  { title: "The Golden Age", artist: "Beck" },
  { title: "The Joker", artist: "Steve Miller Band" },
  { title: "The Long And Winding Road", artist: "Beatles" },
  { title: "The Man Who Sold The World", artist: "David Bowie / Nirvana" },
  { title: "The Middle", artist: "Jimmy Eat World" },
  { title: "The Moon Represents My Heart 月亮代表我的心 Yue Liang Dai Biao Wo De Xin", artist: "Teresa Teng 鄧麗君 Deng Li Jun" },
  { title: "The Night We Met", artist: "Lord Huron" },
  { title: "The One I Love", artist: "REM" },
  { title: "The One That Got Away", artist: "Katy Perry" },
  { title: "The Only Exception", artist: "Paramore" },
  { title: "The Promise", artist: "When In Rome" },
  { title: "The Reason", artist: "Hoobastank" },
  { title: "The Scientist", artist: "Coldplay" },
  { title: "The Way", artist: "Fastball" },
  { title: "The Weight", artist: "The Band" },
  { title: "There She Goes", artist: "The La's / Sixpence None The Richer" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran" },
  { title: "This Year's Love", artist: "David Gray" },
  { title: "Three Little Birds", artist: "Bob Marley" },
  { title: "Tighten Up", artist: "Black Keys" },
  { title: "Time After Time", artist: "Cyndi Lauper" },
  { title: "Times Like These", artist: "Foo Fighters" },
  { title: "Too Close", artist: "Alex Clare" },
  { title: "Torn", artist: "Natalie Imbruglia" },
  { title: "Trouble", artist: "Ray LaMontagne" },
  { title: "Tupelo Honey", artist: "Van Morrison" },
  { title: "Two Princes", artist: "Spin Doctors" },
  { title: "Two Step", artist: "Dave Matthews Band DMB" },
  { title: "U Got It Bad", artist: "Usher" },
  { title: "Under The Bridge", artist: "Red Hot Chili Peppers RHCP" },
  { title: "Undone (The Sweater Song)", artist: "Weezer" },
  { title: "Unwell", artist: "Matchbox Twenty" },
  { title: "Use Somebody", artist: "Kings Of Leon" },
  { title: "Valerie", artist: "Amy Winehouse / Zutons" },
  { title: "Viva La Vida", artist: "Coldplay" },
  { title: "Volcano", artist: "Damien Rice" },
  { title: "Wagon Wheel", artist: "Darius Rucker" },
  { title: "Waiting In Vain", artist: "Bob Marley" },
  { title: "Wake Me Up", artist: "Avicii & Aloe Blacc" },
  { title: "Walking In Memphis", artist: "Marc Cohn" },
  { title: "Walking On The Moon", artist: "The Police" },
  { title: "Waterfalls", artist: "TLC" },
  { title: "Watermelon Sugar", artist: "Harry Styles" },
  { title: "We Found Love", artist: "Rihanna" },
  { title: "What I Got", artist: "Sublime" },
  { title: "What Is Love", artist: "Haddaway" },
  { title: "What Makes A Man", artist: "City And Colour" },
  { title: "What's Up", artist: "4 Non Blondes" },
  { title: "When Doves Cry", artist: "Prince" },
  { title: "When I Come Around", artist: "Green Day" },
  { title: "When I Was Your Man", artist: "Bruno Mars" },
  { title: "When You Were Young", artist: "Killers" },
  { title: "Where Is My Mind", artist: "Pixies" },
  { title: "Where The Streets Have No Name", artist: "U2" },
  { title: "Wherever You Will Go", artist: "The Calling" },
  { title: "White Flag", artist: "Dido" },
  { title: "Who'll Stop The Rain", artist: "Creedence Clearwater Revival CCR" },
  { title: "Wicked Game", artist: "Chris Isaak" },
  { title: "Wild Horses", artist: "Rolling Stones" },
  { title: "Wild World", artist: "Cat Stevens" },
  { title: "Wish You Were Here", artist: "Pink Floyd" },
  { title: "With Arms Wide Open", artist: "Creed" },
  { title: "With Or Without You", artist: "U2" },
  { title: "Without You", artist: "The Kid LAROI" },
  { title: "Wonderful Tonight", artist: "Eric Clapton" },
  { title: "Wonderwall", artist: "Oasis" },
  { title: "Yellow", artist: "Coldplay" },
  { title: "Yellow Ledbetter", artist: "Pearl Jam" },
  { title: "Yellow Submarine", artist: "Beatles" },
  { title: "Yer So Bad", artist: "Tom Petty" },
  { title: "Yesterday", artist: "Beatles" },
  { title: "You And I Both", artist: "Jason Mraz" },
  { title: "You And Me", artist: "Lifehouse" },
  { title: "You Belong With Me", artist: "Taylor Swift" },
  { title: "You Can Call Me Al", artist: "Paul Simon" },
  { title: "You Can't Always Get What You Want", artist: "Rolling Stones" },
  { title: "You May Be Right", artist: "Billy Joel" },
  { title: "You Oughta Know", artist: "Alanis Morissette" },
  { title: "You Were Meant For Me", artist: "Jewel" },
  { title: "You're Beautiful", artist: "James Blunt" },
  { title: "Young Folks", artist: "Peter Bjorn and John" },
  { title: "Your Body Is A Wonderland", artist: "John Mayer" },
  { title: "Your Love", artist: "The Outfield" },
  { title: "Your Song", artist: "Elton John" },
  { title: "Zombie", artist: "Cranberries" }
];

module.exports = songs;
