const songs = [
  { title: "Bohemian Rhapsody", artist: "Queen" },
  { title: "Hotel California", artist: "Eagles" },
  { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd" },
  { title: "Don't Stop Believin'", artist: "Journey" },
  { title: "Wonderwall", artist: "Oasis" },
  { title: "Piano Man", artist: "Billy Joel" },
  { title: "Sweet Caroline", artist: "Neil Diamond" },
  { title: "Livin' on a Prayer", artist: "Bon Jovi" },
  { title: "Mr. Brightside", artist: "The Killers" },
  { title: "Take Me Home, Country Roads", artist: "John Denver" },
  { title: "Hey Jude", artist: "The Beatles" },
  { title: "Superstition", artist: "Stevie Wonder" },
  { title: "Ain't No Sunshine", artist: "Bill Withers" },
  { title: "Lean on Me", artist: "Bill Withers" },
  { title: "Brown Eyed Girl", artist: "Van Morrison" },
  { title: "Folsom Prison Blues", artist: "Johnny Cash" },
  { title: "Ring of Fire", artist: "Johnny Cash" },
  { title: "I Walk the Line", artist: "Johnny Cash" },
  { title: "Fly Me to the Moon", artist: "Frank Sinatra" },
  { title: "The Way You Look Tonight", artist: "Frank Sinatra" },
  { title: "What a Wonderful World", artist: "Louis Armstrong" },
  { title: "Stand by Me", artist: "Ben E. King" },
  { title: "Respect", artist: "Aretha Franklin" },
  { title: "Purple Rain", artist: "Prince" },
  { title: "Let It Be", artist: "The Beatles" },
  { title: "Come Together", artist: "The Beatles" },
  { title: "Imagine", artist: "John Lennon" },
  { title: "Wish You Were Here", artist: "Pink Floyd" },
  { title: "Stairway to Heaven", artist: "Led Zeppelin" },
  { title: "Free Bird", artist: "Lynyrd Skynyrd" },
  { title: "Hallelujah", artist: "Leonard Cohen" },
  { title: "Landslide", artist: "Fleetwood Mac" },
  { title: "Dreams", artist: "Fleetwood Mac" },
  { title: "Go Your Own Way", artist: "Fleetwood Mac" },
  { title: "Rocket Man", artist: "Elton John" },
  { title: "Tiny Dancer", artist: "Elton John" },
  { title: "Bennie and the Jets", artist: "Elton John" },
  { title: "Crocodile Rock", artist: "Elton John" },
  { title: "Your Song", artist: "Elton John" },
  { title: "Under Pressure", artist: "Queen & David Bowie" },
  { title: "Somebody to Love", artist: "Queen" },
  { title: "We Will Rock You", artist: "Queen" },
  { title: "Another One Bites the Dust", artist: "Queen" },
  { title: "Crazy Little Thing Called Love", artist: "Queen" },
  { title: "Africa", artist: "Toto" },
  { title: "Take on Me", artist: "a-ha" },
  { title: "Every Breath You Take", artist: "The Police" },
  { title: "Roxanne", artist: "The Police" },
  { title: "Message in a Bottle", artist: "The Police" },
  { title: "With or Without You", artist: "U2" },
  { title: "Pride (In the Name of Love)", artist: "U2" },
  { title: "Where the Streets Have No Name", artist: "U2" },
  { title: "Zombie", artist: "The Cranberries" },
  { title: "Creep", artist: "Radiohead" },
  { title: "Black Hole Sun", artist: "Soundgarden" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana" },
  { title: "Come as You Are", artist: "Nirvana" },
  { title: "Alive", artist: "Pearl Jam" },
  { title: "Even Flow", artist: "Pearl Jam" },
  { title: "Plush", artist: "Stone Temple Pilots" },
  { title: "Santeria", artist: "Sublime" },
  { title: "What I Got", artist: "Sublime" },
  { title: "Semi-Charmed Life", artist: "Third Eye Blind" },
  { title: "Closing Time", artist: "Semisonic" },
  { title: "Wagon Wheel", artist: "Old Crow Medicine Show" },
  { title: "Harvest Moon", artist: "Neil Young" },
  { title: "Heart of Gold", artist: "Neil Young" },
  { title: "Old Man", artist: "Neil Young" },
  { title: "Fast Car", artist: "Tracy Chapman" },
  { title: "Killing Me Softly", artist: "Roberta Flack" },
  { title: "Summertime", artist: "Ella Fitzgerald" },
  { title: "At Last", artist: "Etta James" },
  { title: "I Put a Spell on You", artist: "Nina Simone" },
  { title: "Feeling Good", artist: "Nina Simone" },
  { title: "Georgia on My Mind", artist: "Ray Charles" },
  { title: "Hit the Road Jack", artist: "Ray Charles" },
  { title: "Dock of the Bay", artist: "Otis Redding" },
  { title: "My Girl", artist: "The Temptations" },
  { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye" },
  { title: "Let's Get It On", artist: "Marvin Gaye" },
  { title: "Sexual Healing", artist: "Marvin Gaye" },
  { title: "Signed, Sealed, Delivered", artist: "Stevie Wonder" },
  { title: "Sir Duke", artist: "Stevie Wonder" },
  { title: "Isn't She Lovely", artist: "Stevie Wonder" },
  { title: "I Just Called to Say I Love You", artist: "Stevie Wonder" },
  { title: "Lovely Day", artist: "Bill Withers" },
  { title: "September", artist: "Earth, Wind & Fire" },
  { title: "Shining Star", artist: "Earth, Wind & Fire" },
  { title: "Boogie Wonderland", artist: "Earth, Wind & Fire" },
  { title: "Le Freak", artist: "Chic" },
  { title: "Good Times", artist: "Chic" },
  { title: "Stayin' Alive", artist: "Bee Gees" },
  { title: "How Deep Is Your Love", artist: "Bee Gees" },
  { title: "Dancing Queen", artist: "ABBA" },
  { title: "Take a Chance on Me", artist: "ABBA" },
  { title: "Mamma Mia", artist: "ABBA" },
  { title: "Waterloo", artist: "ABBA" },
  { title: "Don't Stop Me Now", artist: "Queen" },
  { title: "I Want to Break Free", artist: "Queen" },
  { title: "Radio Ga Ga", artist: "Queen" },
  { title: "Billie Jean", artist: "Michael Jackson" },
  { title: "Thriller", artist: "Michael Jackson" },
  { title: "Beat It", artist: "Michael Jackson" },
  { title: "The Way You Make Me Feel", artist: "Michael Jackson" },
  { title: "Rock with You", artist: "Michael Jackson" },
  { title: "Uptown Funk", artist: "Bruno Mars" },
  { title: "Just the Way You Are", artist: "Bruno Mars" },
  { title: "Treasure", artist: "Bruno Mars" },
  { title: "24K Magic", artist: "Bruno Mars" },
  { title: "Locked Out of Heaven", artist: "Bruno Mars" },
  { title: "Happy", artist: "Pharrell Williams" },
  { title: "Get Lucky", artist: "Daft Punk" },
  { title: "Blinding Lights", artist: "The Weeknd" },
  { title: "Levitating", artist: "Dua Lipa" },
  { title: "Don't Start Now", artist: "Dua Lipa" },
  { title: "Shake It Off", artist: "Taylor Swift" },
  { title: "Love Story", artist: "Taylor Swift" },
  { title: "Blank Space", artist: "Taylor Swift" },
  { title: "Cruel Summer", artist: "Taylor Swift" },
  { title: "Anti-Hero", artist: "Taylor Swift" },
  { title: "Rolling in the Deep", artist: "Adele" },
  { title: "Someone Like You", artist: "Adele" },
  { title: "Hello", artist: "Adele" },
  { title: "Set Fire to the Rain", artist: "Adele" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran" },
  { title: "Shape of You", artist: "Ed Sheeran" },
  { title: "Perfect", artist: "Ed Sheeran" },
  { title: "Photograph", artist: "Ed Sheeran" },
  { title: "Castle on the Hill", artist: "Ed Sheeran" },
  { title: "Viva la Vida", artist: "Coldplay" },
  { title: "Yellow", artist: "Coldplay" },
  { title: "The Scientist", artist: "Coldplay" },
  { title: "Fix You", artist: "Coldplay" },
  { title: "Clocks", artist: "Coldplay" },
  { title: "Use Somebody", artist: "Kings of Leon" },
  { title: "Sex on Fire", artist: "Kings of Leon" },
  { title: "Pumped Up Kicks", artist: "Foster the People" },
  { title: "Radioactive", artist: "Imagine Dragons" },
  { title: "Demons", artist: "Imagine Dragons" },
  { title: "Believer", artist: "Imagine Dragons" },
  { title: "Thunder", artist: "Imagine Dragons" },
  { title: "Ho Hey", artist: "The Lumineers" },
  { title: "Stubborn Love", artist: "The Lumineers" },
  { title: "Home", artist: "Edward Sharpe & The Magnetic Zeros" },
  { title: "Riptide", artist: "Vance Joy" },
  { title: "Budapest", artist: "George Ezra" },
  { title: "Shotgun", artist: "George Ezra" },
  { title: "Hey Ya!", artist: "OutKast" },
  { title: "Roses", artist: "OutKast" },
  { title: "No Diggity", artist: "Blackstreet" },
  { title: "Gangsta's Paradise", artist: "Coolio" },
  { title: "Juicy", artist: "The Notorious B.I.G." },
  { title: "California Love", artist: "2Pac" },
  { title: "Lose Yourself", artist: "Eminem" },
  { title: "In da Club", artist: "50 Cent" },
  { title: "Gold Digger", artist: "Kanye West" },
  { title: "Stronger", artist: "Kanye West" },
  { title: "Crazy in Love", artist: "Beyoncé" },
  { title: "Single Ladies", artist: "Beyoncé" },
  { title: "Halo", artist: "Beyoncé" },
  { title: "Irreplaceable", artist: "Beyoncé" },
  { title: "Umbrella", artist: "Rihanna" },
  { title: "Don't Stop the Music", artist: "Rihanna" },
  { title: "We Found Love", artist: "Rihanna" },
  { title: "Diamonds", artist: "Rihanna" },
  { title: "Yeah!", artist: "Usher" },
  { title: "Burn", artist: "Usher" },
  { title: "No Scrubs", artist: "TLC" },
  { title: "Waterfalls", artist: "TLC" },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston" },
  { title: "Greatest Love of All", artist: "Whitney Houston" },
  { title: "I Will Always Love You", artist: "Whitney Houston" },
  { title: "Like a Prayer", artist: "Madonna" },
  { title: "Material Girl", artist: "Madonna" },
  { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper" },
  { title: "Time After Time", artist: "Cyndi Lauper" },
  { title: "Take My Breath Away", artist: "Berlin" },
  { title: "Total Eclipse of the Heart", artist: "Bonnie Tyler" },
  { title: "I Love Rock 'n' Roll", artist: "Joan Jett" },
  { title: "Barracuda", artist: "Heart" },
  { title: "Alone", artist: "Heart" },
  { title: "Pour Some Sugar on Me", artist: "Def Leppard" },
  { title: "Here I Go Again", artist: "Whitesnake" },
  { title: "Livin' on a Prayer", artist: "Bon Jovi" },
  { title: "You Give Love a Bad Name", artist: "Bon Jovi" },
  { title: "Wanted Dead or Alive", artist: "Bon Jovi" },
  { title: "Welcome to the Jungle", artist: "Guns N' Roses" },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
  { title: "Paradise City", artist: "Guns N' Roses" },
  { title: "November Rain", artist: "Guns N' Roses" },
  { title: "Patience", artist: "Guns N' Roses" },
  { title: "Enter Sandman", artist: "Metallica" },
  { title: "Nothing Else Matters", artist: "Metallica" },
  { title: "Back in Black", artist: "AC/DC" },
  { title: "Thunderstruck", artist: "AC/DC" },
  { title: "Highway to Hell", artist: "AC/DC" },
  { title: "You Shook Me All Night Long", artist: "AC/DC" },
  { title: "TNT", artist: "AC/DC" },
  { title: "Born to Run", artist: "Bruce Springsteen" },
  { title: "Dancing in the Dark", artist: "Bruce Springsteen" },
  { title: "Glory Days", artist: "Bruce Springsteen" },
  { title: "Thunder Road", artist: "Bruce Springsteen" },
  { title: "Born in the U.S.A.", artist: "Bruce Springsteen" },
  { title: "American Girl", artist: "Tom Petty" },
  { title: "Free Fallin'", artist: "Tom Petty" },
  { title: "I Won't Back Down", artist: "Tom Petty" },
  { title: "Mary Jane's Last Dance", artist: "Tom Petty" },
  { title: "Runnin' Down a Dream", artist: "Tom Petty" },
  { title: "Here Comes the Sun", artist: "The Beatles" },
  { title: "Yesterday", artist: "The Beatles" },
  { title: "Twist and Shout", artist: "The Beatles" },
  { title: "I Want to Hold Your Hand", artist: "The Beatles" },
  { title: "A Hard Day's Night", artist: "The Beatles" },
  { title: "While My Guitar Gently Weeps", artist: "The Beatles" },
  { title: "Blackbird", artist: "The Beatles" },
  { title: "Norwegian Wood", artist: "The Beatles" },
  { title: "In My Life", artist: "The Beatles" },
  { title: "All Along the Watchtower", artist: "Jimi Hendrix" },
  { title: "Purple Haze", artist: "Jimi Hendrix" },
  { title: "Voodoo Child", artist: "Jimi Hendrix" },
  { title: "The Wind Cries Mary", artist: "Jimi Hendrix" },
  { title: "Layla", artist: "Eric Clapton" },
  { title: "Tears in Heaven", artist: "Eric Clapton" },
  { title: "Wonderful Tonight", artist: "Eric Clapton" },
  { title: "Cocaine", artist: "Eric Clapton" },
  { title: "Sunshine of Your Love", artist: "Cream" },
  { title: "White Room", artist: "Cream" },
  { title: "Comfortably Numb", artist: "Pink Floyd" },
  { title: "Money", artist: "Pink Floyd" },
  { title: "Another Brick in the Wall", artist: "Pink Floyd" },
  { title: "Time", artist: "Pink Floyd" },
  { title: "Black Dog", artist: "Led Zeppelin" },
  { title: "Whole Lotta Love", artist: "Led Zeppelin" },
  { title: "Kashmir", artist: "Led Zeppelin" },
  { title: "Rock and Roll", artist: "Led Zeppelin" },
  { title: "Ramble On", artist: "Led Zeppelin" },
  { title: "Paint It Black", artist: "The Rolling Stones" },
  { title: "Sympathy for the Devil", artist: "The Rolling Stones" },
  { title: "Gimme Shelter", artist: "The Rolling Stones" },
  { title: "Start Me Up", artist: "The Rolling Stones" },
  { title: "Satisfaction", artist: "The Rolling Stones" },
  { title: "Brown Sugar", artist: "The Rolling Stones" },
  { title: "Jumpin' Jack Flash", artist: "The Rolling Stones" },
  { title: "You Can't Always Get What You Want", artist: "The Rolling Stones" },
  { title: "Space Oddity", artist: "David Bowie" },
  { title: "Heroes", artist: "David Bowie" },
  { title: "Ziggy Stardust", artist: "David Bowie" },
  { title: "Changes", artist: "David Bowie" },
  { title: "Let's Dance", artist: "David Bowie" },
  { title: "Rebel Rebel", artist: "David Bowie" },
  { title: "Starman", artist: "David Bowie" },
  { title: "Life on Mars?", artist: "David Bowie" },
  { title: "Sultans of Swing", artist: "Dire Straits" },
  { title: "Money for Nothing", artist: "Dire Straits" },
  { title: "Walk of Life", artist: "Dire Straits" },
  { title: "Baba O'Riley", artist: "The Who" },
  { title: "Behind Blue Eyes", artist: "The Who" },
  { title: "My Generation", artist: "The Who" },
  { title: "Won't Get Fooled Again", artist: "The Who" },
  { title: "Born to Be Wild", artist: "Steppenwolf" },
  { title: "Fortunate Son", artist: "Creedence Clearwater Revival" },
  { title: "Bad Moon Rising", artist: "Creedence Clearwater Revival" },
  { title: "Proud Mary", artist: "Creedence Clearwater Revival" },
  { title: "Have You Ever Seen the Rain?", artist: "Creedence Clearwater Revival" },
  { title: "Suspicious Minds", artist: "Elvis Presley" },
  { title: "Hound Dog", artist: "Elvis Presley" },
  { title: "Jailhouse Rock", artist: "Elvis Presley" },
  { title: "Can't Help Falling in Love", artist: "Elvis Presley" },
  { title: "Blue Suede Shoes", artist: "Elvis Presley" },
  { title: "Johnny B. Goode", artist: "Chuck Berry" },
  { title: "Tutti Frutti", artist: "Little Richard" },
  { title: "Great Balls of Fire", artist: "Jerry Lee Lewis" },
  { title: "La Bamba", artist: "Ritchie Valens" },
  { title: "That'll Be the Day", artist: "Buddy Holly" },
  { title: "Peggy Sue", artist: "Buddy Holly" },
  { title: "Unchained Melody", artist: "The Righteous Brothers" },
  { title: "You've Lost That Lovin' Feelin'", artist: "The Righteous Brothers" },
  { title: "A Change Is Gonna Come", artist: "Sam Cooke" },
  { title: "Wonderful World", artist: "Sam Cooke" },
  { title: "Cupid", artist: "Sam Cooke" },
  { title: "People Get Ready", artist: "The Impressions" },
  { title: "Mustang Sally", artist: "Wilson Pickett" },
  { title: "Soul Man", artist: "Sam & Dave" },
  { title: "Shout", artist: "The Isley Brothers" },
  { title: "Twist and Shout", artist: "The Isley Brothers" },
  { title: "I Got You (I Feel Good)", artist: "James Brown" },
  { title: "Papa's Got a Brand New Bag", artist: "James Brown" },
  { title: "Get Up Offa That Thing", artist: "James Brown" },
  { title: "Brick House", artist: "Commodores" },
  { title: "Easy", artist: "Commodores" },
  { title: "Three Times a Lady", artist: "Commodores" },
  { title: "All Night Long", artist: "Lionel Richie" },
  { title: "Say You, Say Me", artist: "Lionel Richie" },
  { title: "Hello", artist: "Lionel Richie" },
  { title: "Kiss", artist: "Prince" },
  { title: "When Doves Cry", artist: "Prince" },
  { title: "Let's Go Crazy", artist: "Prince" },
  { title: "1999", artist: "Prince" },
  { title: "Little Red Corvette", artist: "Prince" },
  { title: "Raspberry Beret", artist: "Prince" },
  { title: "Sledgehammer", artist: "Peter Gabriel" },
  { title: "In Your Eyes", artist: "Peter Gabriel" },
  { title: "Invisible Touch", artist: "Genesis" },
  { title: "In the Air Tonight", artist: "Phil Collins" },
  { title: "Against All Odds", artist: "Phil Collins" },
  { title: "Sussudio", artist: "Phil Collins" },
  { title: "Owner of a Lonely Heart", artist: "Yes" },
  { title: "Don't You (Forget About Me)", artist: "Simple Minds" },
  { title: "Everybody Wants to Rule the World", artist: "Tears for Fears" },
  { title: "Shout", artist: "Tears for Fears" },
  { title: "Head Over Heels", artist: "Tears for Fears" },
  { title: "Just Like Heaven", artist: "The Cure" },
  { title: "Lovesong", artist: "The Cure" },
  { title: "Friday I'm in Love", artist: "The Cure" },
  { title: "Boys Don't Cry", artist: "The Cure" },
  { title: "Blue Monday", artist: "New Order" },
  { title: "Bizarre Love Triangle", artist: "New Order" },
  { title: "Love Will Tear Us Apart", artist: "Joy Division" },
  { title: "Personal Jesus", artist: "Depeche Mode" },
  { title: "Enjoy the Silence", artist: "Depeche Mode" },
  { title: "Just Can't Get Enough", artist: "Depeche Mode" },
  { title: "Sweet Dreams", artist: "Eurythmics" },
  { title: "Here Comes the Rain Again", artist: "Eurythmics" },
  { title: "Karma Chameleon", artist: "Culture Club" },
  { title: "Do You Really Want to Hurt Me", artist: "Culture Club" },
  { title: "Relax", artist: "Frankie Goes to Hollywood" },
  { title: "Tainted Love", artist: "Soft Cell" },
  { title: "Don't You Want Me", artist: "The Human League" },
  { title: "Vienna", artist: "Ultravox" },
  { title: "Rio", artist: "Duran Duran" },
  { title: "Hungry Like the Wolf", artist: "Duran Duran" },
  { title: "A View to a Kill", artist: "Duran Duran" },
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers" },
  { title: "Californication", artist: "Red Hot Chili Peppers" },
  { title: "Give It Away", artist: "Red Hot Chili Peppers" },
  { title: "Scar Tissue", artist: "Red Hot Chili Peppers" },
  { title: "Dani California", artist: "Red Hot Chili Peppers" },
  { title: "Can't Stop", artist: "Red Hot Chili Peppers" },
  { title: "Otherside", artist: "Red Hot Chili Peppers" },
  { title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers" },
  { title: "Everlong", artist: "Foo Fighters" },
  { title: "Learn to Fly", artist: "Foo Fighters" },
  { title: "Best of You", artist: "Foo Fighters" },
  { title: "Times Like These", artist: "Foo Fighters" },
  { title: "My Hero", artist: "Foo Fighters" },
  { title: "The Pretender", artist: "Foo Fighters" },
  { title: "Wonderwall", artist: "Oasis" },
  { title: "Don't Look Back in Anger", artist: "Oasis" },
  { title: "Champagne Supernova", artist: "Oasis" },
  { title: "Live Forever", artist: "Oasis" },
  { title: "Song 2", artist: "Blur" },
  { title: "Common People", artist: "Pulp" },
  { title: "Bittersweet Symphony", artist: "The Verve" },
  { title: "Basket Case", artist: "Green Day" },
  { title: "Boulevard of Broken Dreams", artist: "Green Day" },
  { title: "American Idiot", artist: "Green Day" },
  { title: "Good Riddance (Time of Your Life)", artist: "Green Day" },
  { title: "When I Come Around", artist: "Green Day" },
  { title: "All the Small Things", artist: "blink-182" },
  { title: "I Miss You", artist: "blink-182" },
  { title: "Dammit", artist: "blink-182" },
  { title: "What's My Age Again?", artist: "blink-182" },
  { title: "In the End", artist: "Linkin Park" },
  { title: "Numb", artist: "Linkin Park" },
  { title: "Crawling", artist: "Linkin Park" },
  { title: "Somewhere I Belong", artist: "Linkin Park" },
  { title: "Sugar, We're Goin Down", artist: "Fall Out Boy" },
  { title: "Thnks fr th Mmrs", artist: "Fall Out Boy" },
  { title: "The Middle", artist: "Jimmy Eat World" },
  { title: "Ocean Avenue", artist: "Yellowcard" },
  { title: "Iris", artist: "Goo Goo Dolls" },
  { title: "Slide", artist: "Goo Goo Dolls" },
  { title: "1979", artist: "The Smashing Pumpkins" },
  { title: "Tonight, Tonight", artist: "The Smashing Pumpkins" },
  { title: "Bullet with Butterfly Wings", artist: "The Smashing Pumpkins" },
  { title: "Losing My Religion", artist: "R.E.M." },
  { title: "Everybody Hurts", artist: "R.E.M." },
  { title: "It's the End of the World as We Know It", artist: "R.E.M." },
  { title: "Man on the Moon", artist: "R.E.M." },
  { title: "Shiny Happy People", artist: "R.E.M." },
  { title: "Where Is My Mind?", artist: "Pixies" },
  { title: "Debaser", artist: "Pixies" },
  { title: "Lithium", artist: "Nirvana" },
  { title: "Heart-Shaped Box", artist: "Nirvana" },
  { title: "In Bloom", artist: "Nirvana" },
  { title: "About a Girl", artist: "Nirvana" },
  { title: "Jeremy", artist: "Pearl Jam" },
  { title: "Black", artist: "Pearl Jam" },
  { title: "Better Man", artist: "Pearl Jam" },
  { title: "Daughter", artist: "Pearl Jam" },
  { title: "Hunger Strike", artist: "Temple of the Dog" },
  { title: "Man in the Box", artist: "Alice in Chains" },
  { title: "Rooster", artist: "Alice in Chains" },
  { title: "Would?", artist: "Alice in Chains" },
  { title: "Fell on Black Days", artist: "Soundgarden" },
  { title: "Spoonman", artist: "Soundgarden" },
  { title: "Say It Ain't So", artist: "Weezer" },
  { title: "Buddy Holly", artist: "Weezer" },
  { title: "Island in the Sun", artist: "Weezer" },
  { title: "Beverly Hills", artist: "Weezer" },
  { title: "Undone – The Sweater Song", artist: "Weezer" },
  { title: "I Believe in a Thing Called Love", artist: "The Darkness" },
  { title: "Seven Nation Army", artist: "The White Stripes" },
  { title: "Fell in Love with a Girl", artist: "The White Stripes" },
  { title: "Are You Gonna Be My Girl", artist: "Jet" },
  { title: "Last Nite", artist: "The Strokes" },
  { title: "Reptilia", artist: "The Strokes" },
  { title: "Someday", artist: "The Strokes" },
  { title: "Take Me Out", artist: "Franz Ferdinand" },
  { title: "Naive", artist: "The Kooks" },
  { title: "Chelsea Dagger", artist: "The Fratellis" },
  { title: "Fluorescent Adolescent", artist: "Arctic Monkeys" },
  { title: "I Bet You Look Good on the Dancefloor", artist: "Arctic Monkeys" },
  { title: "Do I Wanna Know?", artist: "Arctic Monkeys" },
  { title: "R U Mine?", artist: "Arctic Monkeys" },
  { title: "505", artist: "Arctic Monkeys" },
  { title: "Electric Feel", artist: "MGMT" },
  { title: "Kids", artist: "MGMT" },
  { title: "Time to Pretend", artist: "MGMT" },
  { title: "Somebody That I Used to Know", artist: "Gotye" },
  { title: "Tongue Tied", artist: "Grouplove" },
  { title: "Dog Days Are Over", artist: "Florence + The Machine" },
  { title: "You Make My Dreams", artist: "Hall & Oates" },
  { title: "Rich Girl", artist: "Hall & Oates" },
  { title: "I Can't Go for That", artist: "Hall & Oates" },
  { title: "Maneater", artist: "Hall & Oates" },
  { title: "Rosalita", artist: "Bruce Springsteen" },
  { title: "Badlands", artist: "Bruce Springsteen" },
  { title: "The River", artist: "Bruce Springsteen" },
  { title: "Hungry Heart", artist: "Bruce Springsteen" },
  { title: "Nights on Broadway", artist: "Bee Gees" },
  { title: "Jive Talkin'", artist: "Bee Gees" },
  { title: "Fernando", artist: "ABBA" },
  { title: "SOS", artist: "ABBA" },
  { title: "Knowing Me, Knowing You", artist: "ABBA" },
  { title: "Super Trouper", artist: "ABBA" },
  { title: "The Winner Takes It All", artist: "ABBA" }
];

module.exports = songs;
